version: "3.3"
services:
    db:
        image: postgis/postgis:13-master
        restart: always
        ports:
            - 4321:5432
        volumes:
            - ./etc/postgis:/var/lib/postgis/data
            - ./etc/db-postgis.conf:/etc/postgis/postgis.conf
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=rahasia
            - POSTGRES_DB=ngojeg-admin
        networks:
            - ngojeg-admin

networks:
    ngojeg-admin:
        driver: bridge
